name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: spring-boot-demo2909
  DOCKER_USERNAME: ${{ github.actor }} 
  DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # setup java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
            distribution: 'microsoft'
            java-version: '17'
        # build maven app and create jar file
      - name: Build with Maven
        run: mvn -B package --file pom.xml

        # login in github registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        # build docker image
      - name: Build
        run: docker build . --file Dockerfile --tag ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}:latest

        # push docker image
      - name: Push
        run: docker push ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}:latest